replicaCount: 1
hostNetwork: false
dnsPolicy: ClusterFirst
imagePullPolicy: Always

node:
  name: router

service:
  enabled: true

config: |-
    {
        "adminToken": "",
        "chainConfig": {
          "100": {
          "providers": [
            "https://rpc.gnosischain.com/"
          ]
          },
        "2001": {
            "providers": [
              "https://rpc.c1.milkomeda.com:8545"],
            "minGas": "10000000000000"
          },
        "1": {
          "providers": [
            "https://cloudflare-eth.com"
          ]
        }
        },
        "logLevel": "info",
        "network": "mainnet",
        ## Fill mnemonic operator
        "mnemonic": "",
        ## Fill the router contract address
        "routerContractAddress": "",
        "swapPools": [
            {
            "name": "USDT",
            "assets": [
                {
              "chainId": 100,
              "assetId": "0x4ECaBa5870353805a9F068101A40E0f32ed605C6"
              },
              {
                "chainId": 2001,
                "assetId": "0xab58da63dfdd6b97eaab3c94165ef6f43d951fb2"
              }
            ]
            },   {
                "name": "USDC",
                "assets": [
                {
                  "chainId": 100,
                  "assetId": "0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83"
                  },
                  {
                  "chainId": 2001,
                  "assetId": "0x5a955fddf055f2de3281d99718f5f1531744b102"
                  }
                ]
              }
            ]
        }  

image:
  name: ghcr.io/connext/nxtp-router
  tag: v0.1.34


resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"
services:
  http:
    protocol: TCP
    externalPort: 8080
    internalPort: 8080
  metrics:
    protocol: TCP
    externalPort: 8081
    internalPort: 8081


tolerations: []

affinity: []
