replicaCount: 1
hostNetwork: false
dnsPolicy: ClusterFirst
imagePullPolicy: Always

node:
  name: router

service:
  enabled: true

web3signer: <signer>

### image tag used for the executer, publisher and subscriber ###
image:
  tag: sha-20b6014

resources:
  requests:
    memory: "0.5Gi"
    cpu: "500m"
  limits:
    memory: "1.5Gi"
    cpu: "1000m"

services:
  http:
    protocol: TCP
    externalPort: 8080
    internalPort: 8080
  metrics:
    protocol: TCP
    externalPort: 8081
    internalPort: 8081

services_signer:
  http:
    protocol: TCP
    externalPort: 9000
    internalPort: 9000

tolerations: []

affinity: []
