config: |-
    {
      "redis": {
        "host": "redis-master",
        "port": 6379
      },
      "chains": {
        "6648936": {
          "assets": [
            {
              "address": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
              "name": "USDC"
            }
          ],
          "providers": ["https://eth-mainnet.public.blastapi.io"]
        },
        "1869640809": {
          "assets": [
            {
              "address": "0x67E51f46e8e14D4E4cab9dF48c59ad8F512486DD",
              "name": "nextUSDC"
            }
          ],
          "providers": ["https://optimism-mainnet.public.blastapi.io"]
        },
        "6450786": {
          "providers": ["https://bsc-mainnet.public.blastapi.io"],
          "assets": [
            {
              "address": "0x5e7D83dA751F4C9694b13aF351B30aC108f32C38",
              "name": "nextUSDC"
            }
            ]
            },
        "1886350457": {
          "providers": ["https://polygon-mainnet.public.blastapi.io"],
          "assets": [
            {
              "address": "0xF96C6d2537e1af1a9503852eB2A4AF264272a5B6",
              "name": "nextUSDC"
            }
          ]
        },
        "6778479": {
          "providers": ["https://gnosis-mainnet.public.blastapi.io"],
          "assets": [
            {
              "address": "0x44CF74238d840a5fEBB0eAa089D05b763B73faB8",
              "name": "nextUSDC"
            }
          ]
        },
        "1634886255": {
          "providers": ["https://arb1.arbitrum.io/rpc"],
          "assets": [
            {
              "address": "0x8c556cF37faa0eeDAC7aE665f1Bb0FbD4b2eae36",
              "name": "nextUSDC"
            }
          ]
        }
      },
      "network": "mainnet",
      "logLevel": "debug",
      "server": { "adminToken": "MySecretTokenUnknown" },
      "web3SignerUrl": "http://router-signer-service:9000",
      "messageQueue": {
        "uri": "amqp://guest:guest@rabbitmq:5672"
      }
    }
