apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.node.name }}-pub-node
  labels:
    app.kubernetes.io/instance: {{ .Values.node.name }}-pub-node
    app.kubernetes.io/name: {{ .Values.node.name }}-pub-node
    app.kubernetes.io/version: {{ .Values.image.tag }}
    {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.node.name }}-pub-node
      app.kubernetes.io/name: {{ .Values.node.name }}-pub-node
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Values.node.name }}-pub-node
        app.kubernetes.io/name: {{ .Values.node.name }}-pub-node
        {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 8 }}
        {{- end }}
    spec:
      securityContext: {}
      volumes:
        - configMap:
            defaultMode: 420
            name: config-router
          name: config-router
      containers:
      - name: node
        image: ghcr.io/connext/router-publisher:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /home/node/packages/agents/router/config.json
            name: config-router
            subPath: config.json
        env:
          - name: NXTP_CONFIG
            value: /home/node/packages/agents/router/config.json
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
