apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.node.name }}-executor-executor-node
  labels:
    app.kubernetes.io/instance: {{ .Values.node.name }}-executor-node
    app.kubernetes.io/name: {{ .Values.node.name }}-executor-node
    app.kubernetes.io/part-of: chain-{{ .Values.node.name }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
    {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.node.name }}-executor-node
      app.kubernetes.io/name: {{ .Values.node.name }}-executor-node
      app.kubernetes.io/part-of: chain-{{ .Values.node.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Values.node.name }}-executor-node
        app.kubernetes.io/name: {{ .Values.node.name }}-executor-node
        app.kubernetes.io/part-of: chain-{{ .Values.node.name }}
        {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 8 }}
        {{- end }}
    spec:
      securityContext: {}
      volumes:
        - configMap:
            defaultMode: 420
            name: config-router
          name: config-router
        - secret:
            defaultMode: 420
            secretName: signing-key
          name: signing-key
        - configMap:
            defaultMode: 420
            name: config-signer
          name: config-signer
      containers:
      - name: node
        image: ghcr.io/connext/router-executor:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        volumeMounts:
          - mountPath: /home/node/packages/agents/router/config.json
            name: config-router
            subPath: config.json
        env:
          - name: NXTP_CONFIG
            value: /home/node/packages/agents/router/config.json
      - name: signer
        image: consensys/web3signer:develop
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        volumeMounts:
          - mountPath: /home/node/signer/keyFiles/key.yaml
            name: signing-key
            subPath: key.yaml
          - mountPath:  /home/node/signer/config.yaml
            name: config-signer
            subPath: config.yaml
        args:  
          - "--config-file=/home/node/signer/config.yaml" 
          - "eth1"
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
