{{- if eq $.Values.node.network "mainnet" -}}
apiVersion: v1
kind: Secret
type: Opaque
stringData:
  config.json: |
        {
            "adminToken": "",
            "chainConfig": {
        {{- range $key, $val :=  .Values.chain -}}
        {{- if eq $key "bsc" -}}
            {{- if eq $val.enable  "true" -}}
                "56": {
                "subgraphSyncBuffer": 150,
                "providers": [
                    "{{ join "\",\"" $val.rpc }}"
                ],
            "subgraph": ["https://api.thegraph.com/subgraphs/name/connext/nxtp-bsc", "https://connext-nxtp-subgraph.eu-central-1.bwarelabs.app/subgraphs/name/connext/nxtp-bsc"]
                },
           {{- end -}}
        {{- end -}}
        {{- if eq $key "xdai" -}}
            {{ if eq $val.enable  "true" }}
                "100": {
                "providers": [
                    "{{ join "\",\"" $val.rpc }}"
                ],
            "subgraph": ["https://api.thegraph.com/subgraphs/name/connext/nxtp-xdai", "https://connext-nxtp-subgraph.eu-central-1.bwarelabs.app/subgraphs/name/connext/nxtp-xdai"]
                }
             {{ end }}
        {{- end -}}
        {{- if eq $key "polygon" -}}
            {{- if eq $val.enable  "true" -}}
                "137": {
                "providers": [
                              "{{ join "\",\"" $val.rpc }}"
                ],
                "subgraph": ["https://api.thegraph.com/subgraphs/name/connext/nxtp-matic", "https://connext-nxtp-subgraph.eu-central-1.bwarelabs.app/subgraphs/name/connext/nxtp-matic"],
                "minGas": "100000000000000",
                "confirmations": 60
                }
            {{- end -}}
        {{- end -}}
        {{- if eq $key "fantom" -}}
        {{- if eq $val.enable  "true" -}}
                "250": {
                "providers": [
                    "{{ join "\",\"" $val.rpc }}"
                ],
                "subgraph": ["https://api.thegraph.com/subgraphs/name/connext/nxtp-fantom", "https://connext-nxtp-subgraph.eu-central-1.bwarelabs.app/subgraphs/name/connext/nxtp-fantom"],
                "minGas": "100000000000000",
                "confirmations": 20
                },
        {{- end -}}
        {{- end -}}
        {{- if eq $key "moonriver" -}}
        {{- if eq $val.enable  "true" -}}
                "1285": {
                "providers": [
                    "{{ join "\",\"" $val.rpc }}"
                ]
                },
        {{- end -}}
        {{- end -}}
            {{- if eq $key "arbitrum" }}
            {{- if eq $val.enable  "true" }}
                "42161": {
                "providers": [
                              "{{ join "\",\"" $val.rpc }}"
                ],
                "subgraph": ["https://api.thegraph.com/subgraphs/name/connext/nxtp-arbitrum-one", "https://connext-nxtp-subgraph.eu-central-1.bwarelabs.app/subgraphs/name/connext/nxtp-arbitrum-one"],
                "minGas": "100000000000000"
                },
        {{- end -}}
         {{- end -}}
            {{- if eq $key "avalanche" -}}
            {{- if eq $val.enable  "true" -}}
                "43114": {
                "providers": [
                    "{{ join "\",\"" $val.rpc }}"
                ],
                "subgraph": ["https://api.thegraph.com/subgraphs/name/connext/nxtp-avalanche", "https://connext-nxtp-subgraph.eu-central-1.bwarelabs.app/subgraphs/name/connext/nxtp-avalanche"],
                "minGas": "100000000000000"
                },
            {{- end -}}
            {{- end -}}
            {{- end }} 
            },
            "cleanUpMode": false,
            "logLevel": "info",
            "network": "mainnet",
            "swapPools": [
                {
                "name": "USDT",
                "assets": [
                    {
                    "chainId": 56,
                    "assetId": "0x55d398326f99059fF775485246999027B3197955"
                    },
                    {
                    "chainId": 100,
                    "assetId": "0x4ECaBa5870353805a9F068101A40E0f32ed605C6"
                    },
                    {
                    "chainId": 137,
                    "assetId": "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
                    },
                    {
                    "chainId": 250,
                    "assetId": "0x049d68029688eabf473097a2fc38ef61633a3c7a"
                    },
                    {
                    "chainId": 42161,
                    "assetId": "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
                    },
                    {
                    "chainId": 43114,
                    "assetId": "0xc7198437980c041c805A1EDcbA50c1Ce5db95118"
                    },
                    {
                    "chainId": 1285,
                    "assetId": "0xb44a9b6905af7c801311e8f4e76932ee959c663c"
                    }
                ]
                }
                ]
            }
metadata:
  name: config-router
{{- end -}}